version: "2"
linters:
  enable:
    - errorlint
    - forbidigo
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - misspell
    - revive
    - unconvert
    - unparam
    - wastedassign
  settings:
    gocyclo:
      min-complexity: 12
    govet:
      disable:
        - fieldalignment
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
